<a href="https://colab.research.google.com/github/ChenyuL/Python-Note/blob/master/Datacamp_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to PyTorch

In [ ]:
import torch 
print(torch.tensor([[2,3,5],[1,2,9]]))
torch.rand(2,2)

tensor([[2, 3, 5],
        [1, 2, 9]])


tensor([[0.2616, 0.5432],
        [0.8069, 0.2663]])

In [ ]:
a = torch.rand((3,5,5,9))
# print(a)
a.shape


torch.Size([3, 5, 5, 9])

In [ ]:
torch.Size([3,5])

torch.Size([3, 5])

In [ ]:
import numpy as np
print(np.array([[2,3,5],[1,2,9]]))
np.random.rand(2,2)

[[2 3 5]
 [1 2 9]]


array([[0.2794438 , 0.37435074],
       [0.32345753, 0.59528883]])

## Matrix operations 


In [ ]:
# torch 
a = torch.rand((2,2))
b = torch.rand((2,2))
# multiplication 
print(torch.matmul(a,b))
# element wise operation 
a*b

# zeros and ones
a_torch = torch.zeros(2,2)
b_torch = torch.ones(2,2)
c_torch = torch.eye(2)
print(a_torch,b_torch,c_torch)

tensor([[0.4958, 0.7322],
        [0.5614, 0.5952]])
tensor([[0., 0.],
        [0., 0.]]) tensor([[1., 1.],
        [1., 1.]]) tensor([[1., 0.],
        [0., 1.]])


In [ ]:
# numpy
a = np.random.rand(2,2)
b = np.random.rand(2,2)
print(np.dot(a,b))
# element wise: 
np.multiply(a,b)
a_numpy = np.zeros((2,2))
b_numpy = np.ones((2,2))
c_numpy = np.identity(2)
print(a_numpy,b_numpy,c_numpy)

[[0.25603036 0.3446837 ]
 [0.61129674 0.82685051]]
[[0. 0.]
 [0. 0.]] [[1. 1.]
 [1. 1.]] [[1. 0.]
 [0. 1.]]


In [ ]:
### convert pytorch to numpy 
d_torch = torch.from_numpy(c_numpy)
print(d_torch)
d_numpy = c_torch.numpy()
print(d_numpy)

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)
[[1. 0.]
 [0. 1.]]
